### ISSUE TITLE
E: Package 'mysql-server' has no installation candidate

### ISSUE THREAD

**Issue by 0c0c0f** [baidu-security/openrasp-iast#2]
Building apache-php7.2
Step 1/13 : FROM php:7.2-apache
 ---> daddc1037fdf
Step 2/13 : LABEL MAINTAINER "OpenRASP <ext_yunfenxi@baidu.com>"
 ---> Using cache
 ---> 3efccf26469e
Step 3/13 : ARG RASP_VERSION
 ---> Using cache
 ---> 772c8b71f7da
Step 4/13 : RUN apt-get update &&     apt-get install -y wget unzip libpng-dev mysql-server
 ---> Running in 924ecce0eddc
Get:1 http://security-cdn.debian.org/debian-security buster/updates InRelease [39.1 kB]
Get:2 http://cdn-fastly.deb.debian.org/debian buster InRelease [122 kB]
Get:4 http://security-cdn.debian.org/debian-security buster/updates/main amd64 Packages [99.7 kB]
Get:3 http://cdn-fastly.deb.debian.org/debian buster-updates InRelease [49.3 kB]
Get:5 http://cdn-fastly.deb.debian.org/debian buster/main amd64 Packages [7899 kB]
Get:6 http://cdn-fastly.deb.debian.org/debian buster-updates/main amd64 Packages [5792 B]
Fetched 8214 kB in 19s (433 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Package mysql-server is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'mysql-server' has no installation candidate
ERROR: Service 'apache-php7.2' failed to build: The command '/bin/sh -c apt-get update &&     apt-get install -y wget unzip libpng-dev mysql-server' returned a non-zero code: 100

**Comment by yinhuochong** [comment]
已将 mysql-server 替换为 mariadb-server

**Comment by 0c0c0f** [comment]
支持mac下部署吗？
➜  iast-cloud git:(master) sudo docker-compose up
Password:
Sorry, try again.
Password:
Starting iast-cloud_mongodb3.6_1 ...
Starting iast-cloud_elasticsearch6.4.2_1 ... error
Starting iast-cloud_mysql5.6_1           ...

Starting iast-cloud_mongodb3.6_1         ... error

ERROR: for iast-cloud_mysql5.6_1  Cannot start service mysql5.6: failed to create OCI runtime console socket: mkdir /tmp/pty955692637: permission denied: unknown

ERROR: for iast-cloud_mongodb3.6_1  Cannot start service mongodb3.6: failed to create OCI runtime console socket: mkdir /tmp/pty263926166: permission denied: unknown

ERROR: for elasticsearch6.4.2  Cannot start service elasticsearch6.4.2: failed to create OCI runtime console socket: mkdir /tmp/pty428449105: permission denied: unknown

ERROR: for mysql5.6  Cannot start service mysql5.6: failed to create OCI runtime console socket: mkdir /tmp/pty955692637: permission denied: unknown

ERROR: for mongodb3.6  Cannot start service mongodb3.6: failed to create OCI runtime console socket: mkdir /tmp/pty263926166: permission denied: unknown
ERROR: Encountered errors while bringing up the project.

**Comment by yinhuochong** [comment]
> https://github.com/docker/for-mac/issues/3743
也许你应该向docker官方提交这个问题

**Comment by 0c0c0f** [comment]
好的 多谢回复！
