### ISSUE TITLE
表名位置处的注入无法检测

### ISSUE THREAD

**Issue by stayliv3** [baidu-security/openrasp-iast#3]
ELECT * FROM `'1234`   1234 这里存在注入的时候无法检测。

Notice: sqlfetch called on invalid query resource. The most likely cause is an invalid sqlquery call. Last error returned was: <b>Table 'dvwa.'1234' doesn't exist</b> in query &mdash; SELECT * FROM `'1234` WHERE id = '123' in /var/www/html/core/inc/bigtree/sql.php on line 158

**Comment by yinhuochong** [comment]
用户输入算法的注入检测和注入位置无关，和sql语句中是否完整包含用户输入参数有关

**Comment by stayliv3** [comment]
这个检测特性更新了么

**Comment by CaledoniaProject** [comment]
你先用最新的 1.3.2 测试下哈

**Comment by yinhuochong** [comment]
可否提供下详细的漏洞信息和对应的应用版本？
