### ISSUE TITLE
docker直接启动无法访问

### ISSUE THREAD

**Issue by stayliv3** [baidu-security/openrasp-iast#9]
进入rasp-cloud容易看了下，发现conf文件里配置的80端端口，不是8086，应该是copy conf文件build的时候失败了么，会有这种情况么。我在云主机上直接docker-compose up -d 也无法使用。

**Comment by yinhuochong** [comment]
默认和docker build中的app.conf都没有使用80端口，试试自己手动改回来？

**Comment by stayliv3** [comment]
奇怪，为啥我conf里是80端口，估计是之前改过的缓存？我先试试解决看。
